# Name
spring:
  application:
    name: first
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/helloworld-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: helloworld-client
            authorization-grant-type: authorization_code
            client-authentication-method: none
            scope: openid
            redirect-uri: http://localhost:8081/login/oauth2/code/helloworld-client
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}


# Port
server:
  port: 8081

# API
api:
  url: http://localhost:8082

# Metrics
management:
  observations:
    key-values:
      application: first

# Documentation
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# CORS
service:
  url:
    gateway: http://localhost:8762

# Swagger
swagger:
  app:
    uri: http://localhost:8081
