# Service Name
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/helloworld-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: helloworld-client
            authorization-grant-type: authorization_code
            client-authentication-method: none
            scope: openid
            redirect-uri: http://localhost:8762/login/oauth2/code/helloworld-client
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}

# Server Port
server:
  port: 8762

# Services
service:
  first:
    url: "http://localhost:8081"
  second:
    url: "http://localhost:8082"

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls:
      - name: "First Service"
        url: /aggregate/first-service/v3/api-docs
      - name: "Second Service"
        url: /aggregate/second-service/v3/api-docs
  api-docs:
    enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG