# Service Name
spring:
  application:
    name: gateway

# Server Port
server:
  port: 8762

# Services
service:
  first:
    url: "http://localhost:8081"
  second:
    url: "http://localhost:8082"

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls:
      - name: "First Service"
        url: /aggregate/first-service/v3/api-docs
      - name: "Second Service"
        url: /aggregate/second-service/v3/api-docs
  api-docs:
    enabled: true