version: "4"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
#    volumes:
#      - dbdata:/var/lib/mysql

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./../../realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"

  second:
    image: second-image:0.0.1
    container_name: second-container
    build:
      context: ./../../springcloud-springboot3-swagger3-gateway-keycloak-services_SECOND
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/database
      WAIT_HOSTS: keycloak:8080
      WAIT_TIMEOUT: 60
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/helloworld-realm"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8082:8082
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  first:
    image: first-image:0.0.1
    container_name: first-container
    build:
      context: ./../../springcloud-springboot3-swagger3-gateway-keycloak-services_FIRST
      dockerfile: Dockerfile
    environment:
      API_URL: http://second:8082
      WAIT_HOSTS: keycloak:8080
      WAIT_TIMEOUT: 60
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8080/realms/helloworld-realm"
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s